CREATE DATABASE IF NOT EXISTS kokushin_rental CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kokushin_rental;

CREATE TABLE IF NOT EXISTS cars (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image VARCHAR(255),
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);